# Site settings
title: Lauren Pham
description: A blog about Lauren Pham
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Lauren Pham
user_description: I'm a third year at the Ohio State University, enthusiastically majoring in Electrical and Computer Engineering, focusing on the cross disciplinary application of critical thinking and electrical engineering onto the medical device field. At Ethicon, I’m putting that to use as a Quality Engineering co-op as part of their digital surgery team, learning every day from a great team of people. Next summer, I will be at Stryker Medical in Kalamazoo, Michigan, as an Advanced Operations Intern, looking at another aspect of medical technology. 
user_title: Resume
email: laurenpham23@gmail.com
twitter_username: justphamthings
github_username:  laurenpham
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
